apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel
          image: job_portal
          ports:
            - containerPort: 80
